### PR TITLE
Readme game instructions

### PR DESCRIPTION
**Pull request by sundayezeilo**
A detailed description of this project is documented in the readme file.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require changes
# 🙋‍♂️ team,
You have done a good job so far. Here is one thing you have to do to make this repository more professional🙂.
* [ ] README file explicitly tells how to start the game. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
Kindly add the steps to set up the project on a local machine it is very important.
## That is it, kindly make this change and submit the project for re-review.🤗
Happy coding
Addo

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great work, Congratulation :+1: Project Approved.
You did all changes required previously but I would recommend one more thing:
* [OPTIONAL] Move your instructions about how to start a game in new section with a header `Getting started`. It would allow the user to clearly see it instead of searching for guidance in the `Game Instruction` section.  

Then go ahead and merge to dev_branch.
_Goodluck in your next project_ *Happy coding*

**Comment by ezeilo-su** [comment]
Thank you for all your helpful contributions to this project.

**Pull request merged**
